config/routes.rb
LoginOnly::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :users
  resources :items
  get "/:id" => "items#show"
  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :original_url, :redirect_url
  validates_uniqueness_of :redirect_url
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :username

  
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def after_sign_in_path_for(resource)
    user_path(current_user)
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user, except: :show
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  def show
    @item = Item.find_by_redirect_url(params[:id])
    if @item.nil?
      respond_to do |format|
        format.html {redirect_to "https://support.freee.co.jp/" }
      end
    else
      respond_to do |format|
        format.html {redirect_to URI.encode(@item.original_url) }
      end
    end
  end

  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_path, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    def authenticate_user
      unless current_user
        redirect_to "https://support.freee.co.jp/"
      end
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def after_sign_up_path_for(resource)                                                     
		after_sign_in_path_for(resource)                                                
	end
	def after_inactive_sign_up_path_for(resource)
		welcome_path
	end
end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  http_basic_authenticate_with name: "freee@mentai", password: "freee.mentai"
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end

  def create
    @user = User.new(params[:user])
   
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  http_basic_authenticate_with name: "freee@mentai", password: "freee.mentai"
  def index
  	if current_user 
      redirect_to user_path(current_user)
      return 
    end
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :original_url %><br />
    <%= f.text_field :original_url %>
  </div>
  <div class="field">
    <%= f.label :redirect_url %><br />
    <%= f.text_field :redirect_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Original url</th>
    <th>Redirect url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.original_url %></td>
    <td><%= item.redirect_url %></td>
    <td><%= link_to 'Show', item_path(item.redirect_url) %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Original url:</b>
  <%= @item.original_url %>
</p>

<p>
  <b>Redirect url:</b>
  <%= @item.redirect_url %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>freee|サポートセンター</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.email %>
</p>
<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<%= link_to 'user一覧', users_path %>
<br>
<%= link_to 'url一覧ページ', items_path %>

app/views/welcome/index.html.erb
<%= form_for(:user, url: session_path(:user)) do |f| %>
<div>
   <%= f.text_field :email, placeholder: "ユーザネーム" %>
</div>
<div>
<%= f.password_field :password, placeholder: "パスワード" %>
</div>
<div id="auto_login_wrap">
<%= f.check_box :remember_me %> <%= f.label :"次回から自動的にログインする" %>
</div>
<div id="login_button_wrap">
<%= f.submit('ログイン') %>
</div>               
<% end %>